A preliminary implementation of visicode extension.
alanrtao/VisiCode pull request #2
Opened 2022-11-19 05:26 UTC by LiuHanzhang

Only support image url for now.

2022-11-19 05:47 UTC, LiuHanzhang commented
Only support image url for now.

2022-11-19 06:03 UTC, alanrtao requested changes

2022-11-19 06:03 UTC, alanrtao commented on visicode/example.cpp
> +//!<visicode>
make an examples folder

2022-11-19 06:03 UTC, alanrtao commented on visicode/src/test/suite/extension.test.ts
> +suite('Extension Test Suite', () => {
not really needed?

2022-11-19 06:03 UTC, alanrtao commented on visicode/example.cpp
> +// https://media.npr.org/assets/img/2020/03/27/dualipareal-9f1d672307650164bada30d68c061cbf96777ee2.png
test with data url instead

2022-11-19 06:03 UTC, alanrtao commented on visicode/src/extension.ts
> +		startTagPos = code.indexOf("//!<visicode>", startTagPos)
<visicode> should be enough? not sure what the //! does

2022-11-19 06:03 UTC, alanrtao commented on visicode/src/extension.ts
> +		endTagPos = code.indexOf("//!</visicode>", endTagPos)
same with prev comment

2022-11-19 06:03 UTC, alanrtao commented on visicode/src/extension.ts
> +	while (true) {
can change to for loop, while true looks scary lol
```
for (let startTagPos = ..., endTagPos = ...; startTagPos != -1; startTagPos = ..., endTagPos = ...) {
...
}
```

2022-11-19 06:03 UTC, alanrtao commented on visicode/src/extension.ts
> +		html = 	html + `<img src="${url}">\n\n`
https://stackoverflow.com/questions/25551088/how-to-show-image-using-data-url-in-html-page

The basic one is just getting from API. You can add caching (with another js library maybe) if downloading every time is bad.

Alternatively if the API returns a markdown blob just use https://www.npmjs.com/package/markdown-it or other library to parse it into HTML.

2022-11-19 23:38 UTC, LiuHanzhang commented on visicode/src/test/suite/extension.test.ts
> +suite('Extension Test Suite', () => {
No Idea. Auto-generated by yo

2022-11-19 23:39 UTC, LiuHanzhang commented on visicode/src/extension.ts
> +		startTagPos = code.indexOf("//!<visicode>", startTagPos)
You are right. Not all languages start comment with //

2022-11-20 00:20 UTC, LiuHanzhang commented on visicode/src/extension.ts
> +		startTagPos = code.indexOf("//!<visicode>", startTagPos)
It's a lot more difficult to consider all possible comment symbols. Just assume we use languages whose comments start with '//'

2022-11-28 02:35 UTC, alanrtao approved these changes

2022-11-28 02:35 UTC, merged